site_name: Developing with Call Logs
site_url: https://developers.ringcentral.com
repo_url: https://github.com/ringcentral/developing-with-call-logs
docs_dir: docs
theme: readthedocs
pages:
- ['index.md', 'About', 'Developing with Call Logs']
- ['introduction.md', 'Introduction']
- ['api-basics.md', 'Call Log API Basics']
- ['detailed-call-logs.md', 'Using Detailed Call Log Data']
- ['call-recordings.md', 'Call Recordings']
- ['event-driven-call-log-data.md', 'Event-Driven Call Log Data']
- ['development-concerns.md', 'Development Concerns']
- ['assignments.md', 'Assignments']
